apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: ENVIRONMENT
              value: "PROD"
