apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: server
          image: ghcr.io/pmihaly/learning-k8s:master
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: REDIS_HOST
              value: redis-svc
            - name: REDIS_PORT
              value: "6379"
      imagePullSecrets:
      - name: dockerconfigjson

